version: '2'

services:
    php:
        build:
            context: config/php-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./var/data/uploads/var:/var/www/app/var/uploads
            - ./var/data/uploads/web:/var/www/app/web/uploads
            - ./var/data/indexes:/var/www/app/var/indexes
            - ./var/data/sitemaps:/var/www/app/var/sitemaps
            - ./var/logs/app:/var/www/app/var/logs

            - app-volume:/var/www/app:nocopy
            - cache-volume:/var/www/app/var/cache
            - sessions-volume:/var/www/app/var/sessions
    nginx:
        build: config/nginx
        ports:
            - 10080:80
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx
    mysql:
        build: config/mysql
        ports:
            - 13306:3306
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    elasticsearch:
        build: config/elk/elasticsearch
        ports:
            - 19200:9200
        volumes:
            - ./var/data/elasticsearch:/usr/share/elasticsearch/data
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    logstash:
        build: config/elk/logstash
        ports:
            - 19600:9600
        depends_on:
            - elasticsearch
        volumes:
            - ./var/logs:/var/log/other
    kibana:
        build: config/elk/kibana
        ports:
            - 15601:5601
        depends_on:
            - elasticsearch
            - logstash

volumes:
    app-volume:
        external: true
    cache-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
    sessions-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
